<Project Sdk="MSTest.Sdk">

  <PropertyGroup>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Advent.Common\Advent.Common.csproj" />
    <ProjectReference Include="..\Advent.BaseTests\Advent.BaseTests.csproj" />
  </ItemGroup>

</Project>
